services:
  - type: web
    name: adaptive-vault
    env: python
    region: oregon
    branch: main
    plan: free
    autoDeploy: true

    buildCommand: |
      apt-get update && \
      apt-get install -y --no-install-recommends \
        build-essential gcc libffi-dev libssl-dev python3-dev libxml2-dev libxslt1-dev ssdeep && \
      pip install --upgrade pip setuptools wheel && \
      pip install -r requirements.txt

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"

    healthCheckPath: /
